module WordsHtoM where
import Data.Text (Text)

halist :: [] Text
halist = [ "ha"
         , "habena"
         , "habenula"
         , "habilitas"
         , "habitaculum"
         , "habitatio"
         , "habitatiuncula"
         , "habitator"
         , "habitatrix"
         , "habitio"
         , "habitudo"
         , "habitus"
         , "habrotonum"
         , "hadra"
         , "haecceitas"
         , "haedillus"
         , "haedulus"
         , "haedus"
         , "haematites"
         , "haematologia"
         , "haematophobia"
         , "haemesis"
         , "haereditas"
         , "haeres"
         , "haereseus"
         , "haeresiacus"
         , "haeresis"
         , "haereticus"
         , "haesitantia"
         , "haesitatio"
         , "hafnium"
         , "hagiographus"
         , "haima"
         , "hairo"
         , "halcyon"
         , "halebarda"
         , "halimon"
         , "halipleumon"
         , "halitus"
         , "haliurunna"
         , "halla"
         , "hallebarda"
         , "hallus"
         , "hama"
         , "hamaxostichus"
         , "hamiota"
         , "hammitis"
         , "hamus"
         , "hanappus"
         , "hapsis"
         , "hapsus"
         , "hara"
         , "harena"
         , "harenaria"
         , "harenarium"
         , "harenarius"
         , "harengus"
         , "harenifodina"
         , "hariola"
         , "hariolus"
         , "harmonia"
         , "harpago"
         , "harpastum"
         , "harpe"
         , "harundinetum"
         , "harundo"
         , "haruspex"
         , "haruspicium"
         , "hassium"
         , "hasta"
         , "hastati"
         , "hastile"
         , "haustor"
         , "haustrum"
         , "haustus"
         ]


helist :: [] Text
helist = [ "hebdomada"
         , "hebdomadarius"
         , "hebdomas"
         , "hebenus"
         , "hebetatio"
         , "hebetudo"
         , "hebria"
         , "hecatombe"
         , "hedera"
         , "hedus"
         , "helcium"
         , "helenium"
         , "helicopterum"
         , "heliotropium"
         , "helium"
         , "helix"
         , "hellebarda"
         , "helleborus"
         , "helluatio"
         , "helluo"
         , "helmus"
         , "helops"
         , "Helvetius"
         , "helxine"
         , "hemicrania"
         , "hemina"
         , "hemionus"
         , "hemisphaerium"
         , "hemistichium"
         , "hemo"
         , "hendecasyllabi"
         , "hendecasyllabus"
         , "hepar"
         , "hepatites"
         , "hepatizon"
         , "hephaestitis"
         , "hera"
         , "herb"
         , "herba"
         , "herbaria"
         , "herbarium"
         , "herbarius"
         , "herbitum"
         , "herbula"
         , "heredipeta"
         , "hereditas"
         , "heredium"
         , "heres"
         , "heresis"
         , "Hermes"
         , "hermupoa"
         , "herna"
         , "hernia"
         , "Herodis"
         , "herodius"
         , "herois"
         , "heros"
         , "heroum"
         , "herous"
         , "herpes"
         , "herus"
         , "heterogenia"
         , "hethanim"
         , "hexagonum"
         , "hexameter"
         , "hexas"
         ]

hilist :: [] Text
hilist = [ "hiatus"
         , "Hiber"
         , "hibernaculum"
         , "hibernicus"
         , "hibernum"
         , "Hiberus"
         , "hibiscum"
         , "hibix"
         , "hibrida"
         , "hiemps"
         , "hiems"
         , "hieracitis"
         , "hierarcha"
         , "hierarchia"
         , "hierophylāx"
         , "hilaritas"
         , "hilaritudo"
         , "hillae"
         , "hilum"
         , "hilus"
         , "himantopus"
         , "hinnus"
         , "hinsidia"
         , "hinulus"
         , "hippeus"
         , "hippocampus"
         , "hippocentaurus"
         , "hippodromos"
         , "hippopera"
         , "hippophobas"
         , "hippopotamus"
         , "hippotoxotae"
         , "hippurus"
         , "hir"
         , "hira"
         , "hircus"
         , "hirnea"
         , "hirpex"
         , "hirpus"
         , "hirritus"
         , "hirudo"
         , "hirundo"
         , "hispanus"
         , "histon"
         , "historia"
         , "historicitas"
         , "histrio"
         , "histrix"
         , "hittus"
         ]

holist :: [] Text
holist = [ "hoedus"
         , "hoitzitzillin"
         , "holcus"
         , "holmium"
         , "holocaustoma"
         , "holocaustosis"
         , "holocaustum"
         , "holocautoma"
         , "holus"
         , "homeltium"
         , "homicida"
         , "homicidium"
         , "homilia"
         , "homo"
         , "homoeoteleuton"
         , "homogenia"
         , "homophylophilia"
         , "homosexualitas"
         , "homullus"
         , "homuncio"
         , "homunculus"
         , "honestas"
         , "honestum"
         , "honor"
         , "honorificabilitudinitas"
         , "honorificentia"
         , "honos"
         , "hoplomachos"
         , "hoplomachus"
         , "hora"
         , "horae"
         , "horarium"
         , "hordeolus"
         , "hordeum"
         , "horia"
         , "horizon"
         , "hormenos"
         , "horminum"
         , "hormiscion"
         , "horologium"
         , "horreum"
         , "horripilatio"
         , "horror"
         , "hortatio"
         , "hortator"
         , "hortatus"
         , "hortulanus"
         , "hortulus"
         , "hortus"
         , "hosae"
         , "hospes"
         , "hospicium"
         , "hospitaculum"
         , "hospitale"
         , "hospitalia"
         , "hospitalitas"
         , "hospitator"
         , "hospiticida"
         , "hospitiolum"
         , "hospitium"
         , "hostia"
         , "hostilitas"
         , "hostis"
         , "hostorium"
         , "hostus"
         ]

hulist :: [] Text
hulist = [ "huiuscemodi"
         , "humanitas"
         , "humanus"
         , "humerale"
         , "humerus"
         , "humiditas"
         , "humiliatio"
         , "humilitas"
         , "humor"
         , "humus"
         , "huso"
         , "hutesium"
         ]

hylist :: [] Text
hylist = [ "hyacinthus"
         , "hyaena"
         , "hyalus"
         , "hybrida"
         , "hydra"
         , "hydrargyrum"
         , "hydrargyrus"
         , "hydraulus"
         , "hydria"
         , "hydrodendro"
         , "hydrogenium"
         , "hydrogenum"
         , "hydromantia"
         , "hydromantis"
         , "hydromel"
         , "hydromeli"
         , "hydrophobia"
         , "hydrophobus"
         , "hydropismus"
         , "hydrus"
         , "hyems"
         , "hygra"
         , "hyle"
         , "hymenaeus"
         , "hymnus"
         , "hyoscyamus"
         , "hyoseris"
         , "hyperbole"
         , "hypericon"
         , "hypocauston"
         , "hypocaustum"
         , "hypocrisis"
         , "hypocrita"
         , "hypogaeum"
         , "hypotaurium"
         , "hypotheca"
         , "hypothesis"
         , "hysginum"
         , "hysopum"
         , "hystrix"
         ]

ialist :: [] Text
ialist = [ "i"
         , "iacea"
         , "iactantia"
         , "iactatio"
         , "iactatrix"
         , "iactura"
         , "iactus"
         , "iaculamentum"
         , "iaculatio"
         , "iaculator"
         , "iaculatrix"
         , "iaculum"
         , "iaculus"
         , "iambicus"
         , "iambus"
         , "ianiculum"
         , "ianiculus"
         , "ianitor"
         , "ianthis"
         , "ianua"
         , "ianuarius"
         , "Ianuarius"
         , "ianus"
         , "Iapys"
         , "iasione"
         , "iaspachates"
         , "iaspis"
         , "iasponyx"
         , "iatralipta"
         , "iatraliptice"
         , "iatronices"
         ]

iblist :: [] Text
iblist = [ "Iber"
         , "iberis"
         , "Iberus"
         , "ibex"
         , "ibis"
         , "ibiscum"
         , "ibrida"
         ]

iclist :: [] Text
iclist = [ "icas"
         , "ichneumon"
         , "icon"
         , "icosaedron"
         , "icterias"
         , "icterus"
         , "ictus"
         ]

idlist :: [] Text
idlist = [ "Id"
         , "idea"
         , "identitas"
         , "idiologus"
         , "idioma"
         , "idiota"
         , "idolatra"
         , "idolatria"
         , "idoleum"
         , "idolium"
         , "idololatra"
         , "idololatres"
         , "idololatria"
         , "idolum"
         , "idoneitas"
         , "idus"
         , "Idus"
         ]

ielist :: [] Text
ielist = [ "iecur"
         , "ieiunatio"
         , "ieiunator"
         , "ieiunium"
         , "ientaculum"
         , "ientatio"
         ]

iglist :: [] Text
iglist = [ "ignavia"
         , "ignia"
         , "igniculus"
         , "ignis"
         , "ignitio"
         , "ignobilitas"
         , "ignominia"
         , "ignorantia"
         , "ignoratio"
         ]

illist :: [] Text
illist = [ "ile"
         , "ileos"
         , "ilex"
         , "ilicetum"
         , "illapsus"
         , "illatio"
         , "illecebra"
         , "illegitimus"
         , "illuminatio"
         , "illusio"
         , "illusor"
         , "illuvies"
         ]

imlist :: [] Text
imlist = [ "imaginatio"
         , "imago"
         , "imaguncula"
         , "imbecillitas"
         , "imber"
         , "imbibitium"
         , "imbractum"
         , "imbrex"
         , "imbulus"
         , "imitamentum"
         , "imitatio"
         , "imitator"
         , "imitatrix"
         , "immanitas"
         , "immaturitas"
         , "immemoratio"
         , "immensitas"
         , "immersio"
         , "imminutio"
         , "immissio"
         , "immobilitas"
         , "immoderatio"
         , "immolatio"
         , "immortalitas"
         , "immunditia"
         , "immunitas"
         , "immusulus"
         , "immutabilitas"
         , "immutatio"
         , "imparitas"
         , "impatientia"
         , "impedimentum"
         , "impendium"
         , "impensa"
         , "imperator"
         , "imperatrix"
         , "imperatum"
         , "imperfectio"
         , "imperitia"
         , "imperium"
         , "impertitio"
         , "impes"
         , "impetiginosus"
         , "impetigo"
         , "impetix"
         , "impetus"
         , "impietas"
         , "impilium"
         , "impinguatio"
         , "implementum"
         , "implicatio"
         , "imploratio"
         , "impluvium"
         , "importantia"
         , "importunitas"
         , "impositio"
         , "impossibilitas"
         , "impotentia"
         , "imprecatio"
         , "impressio"
         , "improbatio"
         , "improbitas"
         , "improperium"
         , "imprudentia"
         , "impudentia"
         , "impudicitia"
         , "impulsio"
         , "impulsor"
         , "impulsus"
         , "impunitas"
         , "impuritas"
         , "imputatio"
         , "imum"
         ]

inlist :: [] Text
inlist = [ "ina"
         , "inaequalitas"
         , "inaniloquium"
         , "inauris"
         , "inbecillitas"
         , "Inca"
         , "incantamentum"
         , "incantatio"
         , "incantator"
         , "incarceratio"
         , "incarnatio"
         , "incendiarius"
         , "incendium"
         , "incensio"
         , "incensus"
         , "incentor"
         , "inceptio"
         , "inceptor"
         , "inceptum"
         , "incertus"
         , "incessus"
         , "incestus"
         , "incidentia"
         , "incile"
         , "incineratio"
         , "incingulum"
         , "incisio"
         , "incisura"
         , "incitabilitas"
         , "incitabulum"
         , "incitamentum"
         , "incitatio"
         , "incitega"
         , "inclinatio"
         , "inclusio"
         , "inclusor"
         , "incogitantia"
         , "incola"
         , "incolatus"
         , "incolumitas"
         , "incommensurabilitas"
         , "incommobilitas"
         , "inconstantia"
         , "incontinentia"
         , "incorporatio"
         , "incorruptela"
         , "incorruptibilitas"
         , "incorruptio"
         , "incredulitas"
         , "incrementum"
         , "increpatio"
         , "incriminatio"
         , "incrustatio"
         , "incubo"
         , "incubus"
         , "incumulatio"
         , "incunabulum"
         , "incuria"
         , "incursatio"
         , "incursio"
         , "incursus"
         , "incus"
         , "indagatio"
         , "indago"
         , "indemnitas"
         , "index"
         , "indicatio"
         , "indicator"
         , "indicatura"
         , "indicina"
         , "indicium"
         , "indiciva"
         , "indictio"
         , "indiculum"
         , "indiculus"
         , "indifferentia"
         , "indigena"
         , "indigentia"
         , "indigenus"
         , "indigitamenta"
         , "indignatio"
         , "indignitas"
         , "indiligentia"
         , "indiscretio"
         , "inditio"
         , "inditor"
         , "indium"
         , "individuum"
         , "indolentia"
         , "indoles"
         , "inducia"
         , "inductio"
         , "inductor"
         , "inductorium"
         , "inductrix"
         , "inductura"
         , "inducula"
         , "indulgentia"
         , "indumentum"
         , "induratio"
         , "indusiarius"
         , "indusium"
         , "industria"
         , "indutia"
         , "inebriatio"
         , "ineptia"
         , "ineptitudo"
         , "inertia"
         , "ineruditio"
         , "infacetia"
         , "infamia"
         , "infans"
         , "infantia"
         , "infanticida"
         , "infanticidium"
         , "infantula"
         , "infantulus"
         , "infarctus"
         , "infectio"
         , "infectus"
         , "infelicitas"
         , "inferia"
         , "inferna"
         , "inferni"
         , "infernum"
         , "infernus"
         , "inficetia"
         , "infidelitas"
         , "infinitivus"
         , "infinitum"
         , "infirmaria"
         , "infirmarius"
         , "infirmatio"
         , "infirmitas"
         , "inflammatio"
         , "inflatio"
         , "inflectio"
         , "inflexio"
         , "inflictio"
         , "influentia"
         , "influxus"
         , "informatio"
         , "infortunium"
         , "infrigidatio"
         , "infula"
         , "infundibulum"
         , "infusio"
         , "ingeniarius"
         , "ingeniator"
         , "ingenium"
         , "ingenuitas"
         , "ingluvies"
         , "ingratitudo"
         , "ingressio"
         , "ingressus"
         , "inguen"
         , "inhabilitas"
         , "inhabitatio"
         , "inhabitator"
         , "inhibitio"
         , "inhonoratio"
         , "inhospitalitas"
         , "inhumanitas"
         , "iniectio"
         , "inimicitia"
         , "inimicus"
         , "iniquitas"
         , "initiatio"
         , "initium"
         , "initus"
         , "iniucunditas"
         , "iniunctio"
         , "iniuria"
         , "iniuriator"
         , "iniustitia"
         , "iniectio"
         , "iniucunditas"
         , "iniunctio"
         , "iniustitia"
         , "inlecebra"
         , "inluminatio"
         , "inlusio"
         , "inlusor"
         , "inluvies"
         , "inmanitas"
         , "inmemoratio"
         , "inmissio"
         , "inmobilitas"
         , "inmortalitas"
         , "inmunditia"
         , "inmunitas"
         , "inmutatio"
         , "innocentia"
         , "innovatio"
         , "inoboedientia"
         , "inobservantia"
         , "inoculatio"
         , "inopia"
         , "inordinatio"
         , "inpedimentum"
         , "inpendium"
         , "inpensa"
         , "inperitia"
         , "inpes"
         , "inpetiginosus"
         , "inpetigo"
         , "inplicatio"
         , "inpositio"
         , "inpotentia"
         , "inprecatio"
         , "inprobatio"
         , "inprobitas"
         , "inproperium"
         , "inprudentia"
         , "inpudentia"
         , "inpudicitia"
         , "inpulsio"
         , "inpunitas"
         , "inpuritas"
         , "inquietudo"
         , "inquilina"
         , "inquilinatus"
         , "inquilinus"
         , "inquinamentum"
         , "inquinatio"
         , "inquisitio"
         , "inquisitor"
         , "inreverentia"
         , "inrigatio"
         , "inrisio"
         , "inritatio"
         , "inritator"
         , "inritatrix"
         , "inrogatio"
         , "inruptio"
         , "insania"
         , "insapientia"
         , "inscientia"
         , "inscitia"
         , "inscriptio"
         , "insectatio"
         , "insecticida"
         , "insectum"
         , "insertio"
         , "insidia"
         , "insidiae"
         , "insidiator"
         , "insidiatrix"
         , "insigne"
         , "insignitor"
         , "insimulatio"
         , "insinuatio"
         , "insinuator"
         , "insinuatrix"
         , "insipientia"
         , "insitio"
         , "insitor"
         , "insolatio"
         , "insolentia"
         , "insomnia"
         , "insomnietas"
         , "inspectio"
         , "inspiratio"
         , "inst"
         , "instabilitas"
         , "instantia"
         , "instar"
         , "instauratio"
         , "instimulator"
         , "instinctus"
         , "instita"
         , "institor"
         , "institutio"
         , "institutor"
         , "institutum"
         , "instructio"
         , "instructor"
         , "instructura"
         , "instrumentum"
         , "insubulum"
         , "insula"
         , "insulanus"
         , "insularius"
         , "insulsitas"
         , "insultus"
         , "insurrectio"
         , "integimentum"
         , "integralitas"
         , "integratio"
         , "integritas"
         , "integritudo"
         , "integumentum"
         , "intellectio"
         , "intellectus"
         , "intellegentia"
         , "intelligentia"
         , "intemperantia"
         , "intempestivitas"
         , "intempestum"
         , "intensio"
         , "intensitas"
         , "intentio"
         , "intercapedo"
         , "interceptio"
         , "intercessio"
         , "intercessor"
         , "intercestrix"
         , "intercolumnium"
         , "interdictio"
         , "interdictor"
         , "interdictum"
         , "interfatio"
         , "interfectio"
         , "interfector"
         , "interfectrix"
         , "interiectio"
         , "interiectura"
         , "interitio"
         , "interitus"
         , "interiectio"
         , "interiectura"
         , "interlunium"
         , "intermissio"
         , "internecida"
         , "internecio"
         , "internicio"
         , "interpellatio"
         , "interpellator"
         , "interpositio"
         , "interpres"
         , "interpretatio"
         , "interprex"
         , "interpunctio"
         , "interregnum"
         , "interrete"
         , "interrex"
         , "interrogamentum"
         , "interrogatio"
         , "interrogatiuncula"
         , "interrogator"
         , "interruptio"
         , "intersectio"
         , "interstitio"
         , "interstitium"
         , "intertrigo"
         , "intertrimentum"
         , "interturbatio"
         , "interula"
         , "intervallum"
         , "interventio"
         , "interventus"
         , "intestina"
         , "intibus"
         , "intimatio"
         , "intolerantia"
         , "intributio"
         , "introductio"
         , "introductor"
         , "introitus"
         , "intubum"
         , "intubus"
         , "intuitus"
         , "intybus"
         , "inula"
         , "inundatio"
         , "inutilitas"
         , "invasio"
         , "inventarium"
         , "inventio"
         , "inventor"
         , "inventrix"
         , "investigatio"
         , "investigator"
         , "invidentia"
         , "invidia"
         , "invisibilitas"
         , "invitamentum"
         , "invitatio"
         , "invocatio"
         , "involucrum"
         , "involumentum"
         , "involvulus"
         ]

iolist :: [] Text
iolist = [ "iobeleus"
         , "iocatio"
         , "ioculator"
         , "iocunditas"
         , "iocur"
         , "iocus"
         , "iodium"
         , "iodum"
         , "iogurtum"
         , "iotacismus"
         , "ioth"
         ]

irlist :: [] Text
irlist = [ "ir"
         , "ira"
         , "iracundia"
         , "iridium"
         , "irio"
         , "ironia"
         , "irregularitas"
         , "irreverentia"
         , "irrigatio"
         , "irrisio"
         , "irrisor"
         , "irritatio"
         , "irritator"
         , "irritatrix"
         , "irritus"
         , "irrogatio"
         , "irroratio"
         , "irrumatio"
         , "irrumator"
         , "irruptio"
         ]

islist :: [] Text
islist = [ "isagoge"
         , "isatis"
         , "ischias"
         , "ischion"
         , "ischium"
         , "ischuria"
         , "isicium"
         , "Islandus"
         , "islandus"
         , "isotopium"
         , "isotopus"
         , "Israelita"
         , "Israhelita"
         , "isthmus"
         , "Istrahelita"
         ]

itlist :: [] Text
itlist = [ "italus"
         , "iter"
         , "iteratio"
         , "itinerans"
         , "itinerarium"
         , "itio"
         , "itus"
         ]

iulist :: [] Text
iulist = [ "iuba"
         , "iubar"
         , "iubilatio"
         , "iucundatio"
         , "iucunditas"
         , "iudaeus"
         , "iudaismus"
         , "iudex"
         , "iudicatio"
         , "iudicator"
         , "iudicatrix"
         , "iudicatum"
         , "iudicatus"
         , "iudicium"
         , "iugalitas"
         , "iugatio"
         , "iuger"
         , "iugerum"
         , "iuglans"
         , "iugulum"
         , "iugum"
         , "iulis"
         , "iulus"
         , "iumentum"
         , "iuncetum"
         , "iunctio"
         , "iunctura"
         , "iuncus"
         , "iuniperus"
         , "iunix"
         , "Iunonicola"
         , "iuramentum"
         , "iurandum"
         , "iuratio"
         , "iurator"
         , "iureconsultus"
         , "iurgium"
         , "iuridicus"
         , "iurisconsultus"
         , "iurisdictio"
         , "iurisprudentia"
         , "iurista"
         , "ius"
         , "iuscularius"
         , "iusculum"
         , "iusiurandum"
         , "iussio"
         , "iussus"
         , "iusta"
         , "iusticiaria"
         , "iusticiarius"
         , "iustificatio"
         , "iustificator"
         , "iustitia"
         , "iustitiaria"
         , "iustitiarius"
         , "iustitium"
         , "iuvenca"
         , "iuvencus"
         , "iuvenis"
         , "iuventa"
         , "iuventas"
         , "iuventus"
         , "ix"
         , "ixon"
         , "iynx"
         ]



























































