module WordsNtoS where
import Data.Text (Text)

nalist :: [] Text
nalist = [ "nabla"
         , "nablium"
         , "nablum"
         , "nabun"
         , "nacca"
         , "naenia"
         , "Naepor"
         , "naevus"
         , "nana"
         , "nanotechnologia"
         , "nans"
         , "nanus"
         , "naphtha"
         , "napina"
         , "naptha"
         , "napura"
         , "napus"
         , "narcissitis"
         , "narcissus"
         , "nardus"
         , "naris"
         , "narita"
         , "narratio"
         , "narratus"
         , "narta"
         , "nartatio"
         , "nasamonitis"
         , "nascentia"
         , "nasica"
         , "Nasiraeus"
         , "nasiterna"
         , "nassa"
         , "nasturtium"
         , "nasus"
         , "nata"
         , "natalis"
         , "natatio"
         , "natator"
         , "naticidium"
         , "natio"
         , "natis"
         , "nativitas"
         , "natrium"
         , "natrix"
         , "natula"
         , "natura"
         , "naturalitas"
         , "natus"
         , "nauarchus"
         , "nauci"
         , "nauclerus"
         , "naucum"
         , "naucus"
         , "naufragium"
         , "naufragus"
         , "naulum"
         , "naumachia"
         , "nausia"
         , "nausum"
         , "nauta"
         , "nautilus"
         , "navale"
         , "navicella"
         , "navicula"
         , "navigatio"
         , "navigator"
         , "navigium"
         , "navis"
         , "navita"
         , "navitas"
         , "navities"
         , "Nazaraeus"
         , "Nazareus"
         , "Naziraeus"
         ]


nelist :: [] Text
nelist = [ "neanias"
         , "nebritis"
         , "nebrundines"
         , "nebula"
         , "nebulo"
         , "necator"
         , "necatrix"
         , "necessaria"
         , "necessarium"
         , "necessarius"
         , "necessitas"
         , "necessitudo"
         , "necrologium"
         , "necromantia"
         , "necrophilia"
         , "nectar"
         , "necydalus"
         , "nederlandus"
         , "nefas"
         , "nefrones"
         , "negatio"
         , "negator"
         , "neglectio"
         , "neglector"
         , "neglectus"
         , "neglegentia"
         , "negotiatio"
         , "negotiator"
         , "negotium"
         , "negrities"
         , "nema"
         , "nemesis"
         , "nemus"
         , "nenia"
         , "neodymium"
         , "neomenia"
         , "neon"
         , "neophytus"
         , "neopum"
         , "nepa"
         , "nepeta"
         , "nepos"
         , "nepotatio"
         , "neptis"
         , "neptunium"
         , "nequitia"
         , "Nereis"
         , "nerion"
         , "nerita"
         , "nerium"
         , "nervulus"
         , "nervus"
         , "nestis"
         , "nete"
         , "neuroides"
         , "neutron"
         , "nex"
         , "nexilitas"
         , "nexio"
         , "nexus"
         ]


nilist :: [] Text
nilist = [ "niccolum"
         , "nidor"
         , "nidulus"
         , "nidus"
         , "nigredo"
         , "nigritia"
         , "nigrities"
         , "nigritudo"
         , "nigriventer"
         , "nihil"
         , "nihildum"
         , "nihilo"
         , "nihilum"
         , "nil"
         , "nilios"
         , "nilum"
         , "nilus"
         , "nimbus"
         , "nimietas"
         , "ningor"
         , "ninguis"
         , "niobium"
         , "nisus"
         , "nitedula"
         , "nitela"
         , "nitiditas"
         , "nitor"
         , "nitrogenium"
         , "nitrum"
         , "nix"
         , "nixus"
         ]

nolist :: [] Text
nolist = [ "nobelium"
         , "nobilitas"
         , "nocticola"
         , "noctifer"
         , "noctiluca"
         , "noctua"
         , "nocumentum"
         , "nodamen"
         , "nodatio"
         , "nodia"
         , "nodositas"
         , "nodulus"
         , "nodus"
         , "noegeum"
         , "nola"
         , "noluntas"
         , "Nomas"
         , "nomen"
         , "nomenclator"
         , "nomenclatura"
         , "nomenculator"
         , "nominatio"
         , "nomisma"
         , "Non"
         , "nonae"
         , "noneolae"
         , "nonna"
         , "nonnemo"
         , "nonnihil"
         , "nonnus"
         , "norma"
         , "normatio"
         , "northus"
         , "nosema"
         , "nosocomium"
         , "nosodochium"
         , "nota"
         , "notarius"
         , "notatio"
         , "notio"
         , "notitia"
         , "notula"
         , "noumen"
         , "nova"
         , "novacula"
         , "novalis"
         , "novella"
         , "novellae"
         , "novelletum"
         , "novemvir"
         , "novemviratus"
         , "novena"
         , "noverca"
         , "novilunium"
         , "novitas"
         , "novus"
         , "nox"
         , "noxa"
         , "noxia"
         , "noxitudo"
         ]

nulist :: [] Text
nulist = [ "nubecula"
         , "nubes"
         , "nubicula"
         , "nubilarium"
         , "nubilum"
         , "nubis"
         , "nucetum"
         , "nucha"
         , "nucifrangibulum"
         , "nucleus"
         , "nuculeus"
         , "nuditas"
         , "nuga"
         , "nugacitas"
         , "nugae"
         , "nugator"
         , "nullitas"
         , "numella"
         , "numen"
         , "numerarius"
         , "numeratio"
         , "numerator"
         , "numerositas"
         , "numerus"
         , "Numida"
         , "numisma"
         , "nummularius"
         , "nummulus"
         , "nummus"
         , "numus"
         , "nuncius"
         , "nuncupatio"
         , "nuncupator"
         , "nundinae"
         , "nundinatio"
         , "nuntia"
         , "nuntiatio"
         , "nuntium"
         , "nuntius"
         , "nupta"
         , "nuptia"
         , "nuptiae"
         , "nuptus"
         , "nurus"
         , "nutatio"
         , "nutricio"
         , "nutricula"
         , "nutrimentum"
         , "nutritio"
         , "nutrix"
         , "nutus"
         , "nux"
         ]

nylist :: [] Text
nylist = [ "nyctalopa"
         , "nycticorax"
         , "nympha"
         , "nymphaea"
         , "nymphe"
         , "nympheum"
         ]

oblist :: [] Text
oblist = [ "obaerarius"
         , "obaeratus"
         , "obambulatio"
         , "obauditio"
         , "obauditus"
         , "obba"
         , "obdensatio"
         , "obductio"
         , "obduratio"
         , "obeditio"
         , "obeliscus"
         , "obesitas"
         , "obex"
         , "obiectatio"
         , "obiectio"
         , "obiectum"
         , "obiectus"
         , "obituarius"
         , "obitus"
         , "obiurgatio"
         , "obiectio"
         , "obiectum"
         , "obiex"
         , "obiurgatio"
         , "oblatio"
         , "oblectamentum"
         , "oblectatio"
         , "obligatio"
         , "obliquitas"
         , "obliteratio"
         , "oblivio"
         , "oblivium"
         , "oblocutio"
         , "obloquium"
         , "obnubilatio"
         , "oboedientia"
         , "oboeditio"
         , "obolus"
         , "obprobrium"
         , "obrogatio"
         , "obrussa"
         , "obryzum"
         , "obscenitas"
         , "obscuratio"
         , "obscuritas"
         , "obscurum"
         , "obsecratio"
         , "obsequentia"
         , "obsequiae"
         , "obsequium"
         , "observantia"
         , "observatio"
         , "observatus"
         , "obses"
         , "obsessio"
         , "obsessor"
         , "obsetrix"
         , "obsidio"
         , "obsidium"
         , "obsignator"
         , "obsonium"
         , "obstaculum"
         , "obstetrix"
         , "obstinatio"
         , "obstructio"
         , "obtentio"
         , "obtentus"
         , "obtestatio"
         , "obtrectatio"
         , "obtrectator"
         , "obturatio"
         , "obtusio"
         , "obtutus"
         , "obumbratio"
         ]

oclist :: [] Text
oclist = [ "occa"
         , "occasio"
         , "occasus"
         , "occidens"
         , "occidio"
         , "occipitium"
         , "occipitum"
         , "occiput"
         , "occisio"
         , "occisor"
         , "Occitanus"
         , "occultatio"
         , "occupatio"
         , "occursatio"
         , "occursator"
         , "occursio"
         , "occursus"
         , "oceanus"
         , "ocellus"
         , "ocimum"
         , "oclus"
         , "ocrea"
         , "ocris"
         , "octaedron"
         , "octaedros"
         , "octans"
         , "octaphoron"
         , "octarius"
         , "octavius"
         , "octophoron"
         , "octopus"
         , "octovir"
         , "octoviratus"
         , "ocularius"
         , "oculus"
         ]

odlist :: [] Text
odlist = [ "OD"
         , "oda"
         , "odinolytes"
         , "odium"
         , "odor"
         , "odoramentum"
         , "odoratus"
         , "odos"
         ]

oelist :: [] Text
oelist = [ "oecologia"
         , "oeconomia"
         , "oecosystema"
         , "oenanthium"
         , "oenomania"
         , "oenopola"
         , "oephi"
         , "oestrus"
         , "oesypum"
         , "oetum"
         ]

oflist :: [] Text
oflist = [ "offa"
         , "offendiculum"
         , "offendix"
         , "offendo"
         , "offensio"
         , "offensiuncula"
         , "offensus"
         , "offertorium"
         , "offex"
         , "officialis"
         , "officiarius"
         , "officina"
         , "officium"
         , "offla"
         , "offula"
         , "offuscatio"
         , "oica"
         ]

ollist :: [] Text
ollist = [ "ola"
         , "olea"
         , "oleamen"
         , "oleamentum"
         , "oleaster"
         , "oleitas"
         , "olentia"
         , "olentica"
         , "olenticetum"
         , "oleositas"
         , "oletum"
         , "oleum"
         , "olfactoriolum"
         , "olfactorium"
         , "olfactus"
         , "oligarcha"
         , "oligarchia"
         , "Olipor"
         , "oliva"
         , "olivetum"
         , "olivitas"
         , "olla"
         , "olma"
         , "olor"
         , "olus"
         , "olvatium"
         , "olyra"
         ]

omlist :: [] Text
omlist = [ "omasum"
         , "ombria"
         , "omen"
         , "omentum"
         , "ommatidium"
         , "omnia"
         , "omnipotentia"
         , "omphacium"
         ]

onlist :: [] Text
onlist = [ "onager"
         , "oncidium"
         , "onere"
         , "oniros"
         , "oniscus"
         , "onocentaurus"
         , "onocrotalus"
         , "onolatria"
         , "onoma"
         , "onomatopeia"
         , "onomatopoeia"
         , "ononis"
         , "onopyxos"
         , "onus"
         , "onycha"
         , "onyx"
         ]

oplist :: [] Text
oplist = [ "oogenesis"
         , "op"
         , "opacitas"
         , "opalus"
         , "opella"
         , "opera"
         , "operarius"
         , "operatio"
         , "operator"
         , "operculum"
         , "operimentum"
         , "operositas"
         , "opertorium"
         , "opertum"
         , "opetis"
         , "ophicardelos"
         , "ophiomachus"
         , "ophites"
         , "opifex"
         , "opificium"
         , "opilio"
         , "opinio"
         , "opitulatio"
         , "opium"
         , "opobalsametum"
         , "oportunitas"
         , "oppid"
         , "oppidanus"
         , "oppidum"
         , "oppilatio"
         , "opportunitas"
         , "oppositio"
         , "oppositus"
         , "oppressio"
         , "opprobrium"
         , "oppugnatio"
         , "oppugnator"
         , "ops"
         , "opsequium"
         , "optimas"
         , "optio"
         , "optumas"
         , "opulentia"
         , "opulentitas"
         , "opulus"
         , "opupa"
         , "opus"
         , "opusculum"
         ]

orlist :: [] Text
orlist = [ "ora"
         , "oraclum"
         , "oraculum"
         , "orans"
         , "orarium"
         , "oratio"
         , "orator"
         , "oratrix"
         , "oratus"
         , "orbiculus"
         , "orbis"
         , "orbita"
         , "orbitas"
         , "orbitudo"
         , "orca"
         , "orchesta"
         , "orchestra"
         , "orchis"
         , "orcus"
         , "ordinariatus"
         , "ordinarius"
         , "ordinatio"
         , "ordinator"
         , "ordo"
         , "oreae"
         , "Oreas"
         , "orestion"
         , "orexis"
         , "orfanus"
         , "organa"
         , "organicus"
         , "organismus"
         , "organum"
         , "orgia"
         , "orichalcum"
         , "oricilla"
         , "oricla"
         , "oricula"
         , "oriens"
         , "orificium"
         , "origanum"
         , "originarius"
         , "origo"
         , "oritis"
         , "ormenos"
         , "ornamentum"
         , "ornatrix"
         , "ornatus"
         , "ornithologia"
         , "ornithorhynchus"
         , "ornus"
         , "orobus"
         , "orphanus"
         , "orthographia"
         , "ortus"
         , "ortygometra"
         , "ortyx"
         , "oryctognosia"
         , "oryctologia"
         , "oryx"
         , "oryza"
         ]

oslist :: [] Text
oslist = [ "OS"
         , "oscen"
         , "oscillatio"
         , "oscillum"
         , "osculatio"
         , "osculum"
         , "osmium"
         , "ossarium"
         , "ossifragus"
         , "ossilago"
         , "ossuarium"
         , "ossum"
         , "ostensio"
         , "ostentatio"
         , "ostentum"
         , "ostes"
         , "ostiarius"
         , "ostigo"
         , "ostiolum"
         , "ostium"
         , "ostracias"
         , "ostracitis"
         , "ostrea"
         , "ostrearium"
         , "ostreum"
         , "ostriago"
         , "ostrum"
         , "osyris"
         ]

otlist :: [] Text
otlist = [ "othonna"
         , "otion"
         , "otiositas"
         , "otis"
         , "otium"
         , "otus"
         , "ovatus"
         , "ovicula"
         , "ovile"
         , "ovis"
         , "ovum"
         , "oxalis"
         , "oxidum"
         , "oxydatum"
         , "oxydendro"
         , "oxygenium"
         , "oxygenum"
         , "oxymyrsine"
         , "oxynosema"
         , "oxytropis"
         , "ozaena"
         ]







































